### ISSUE TITLE
Module zeroclipboard not found

### ISSUE THREAD

**Issue by ghost** [handsontable/hot-builder#11]
I'm not sure what I'm doing wrong here.

`"hot-builder": "0.4.1"`

If I follow the directions and run...

```
npm install -g hot-builder
hot-builder build -o dist/handsontable
```

I get `Module zeroclipboard not found` and that's the end of it.

I've tried `npm install -S zeroclipboard` just for kicks, but nothing seems to work.

Any ideas? The only reason I'm using hot-builder is because when I try to run browserify across the manually-downloaded `handsontable.js` I get this error: 

```
handsontable:16
import './shims/classes';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

I just want to use this tool!

**Comment by budnix** [comment]
Which version of npm and node do you use?

**Comment by ghost** [comment]
4.2.1

**Comment by budnix** [comment]
and npm? :)

**Comment by ghost** [comment]
Sorry, too early: node 4.2.1, npm 3.3.6.

**Comment by budnix** [comment]
Confirm, there is a bug. Tested in npm@1, npm@2 and npm@3.

**Comment by budnix** [comment]
Hi again, We released yesterday new version of Handsontable which should resolve hot-builder problems. Can you remove hot-builder (`npm uninstall hot-builder -g`) and add it again? After that everything should be working fine.

**Comment by IntegerMan** [comment]
For what it's worth, this may have recurred. I'm working with support currently on the matter, but am marking it here as well for the interwebs.
