### ISSUE TITLE
pro version build problem

### ISSUE THREAD

**Issue by hadesz** [handsontable/hot-builder#13]
Hello,

I'm trying to build a pro version package, and got the following error:
"Input package file is not valid. It must point to a package.json file from Handsontable or HandsontablePro project."

the folder I tried the command was your cloned git repo, the 1.1.1 tag was checked out
"hot-builder build -o ./dist --input package.json"

any idea?

thanks,
David

**Comment by t-kawajiri** [comment]
I got same error, too.  My version is 1.2.0

**Comment by AMBudnik** [comment]
Thanks for reporting @hadesz and @t-kawajiri we'll check it
Do you have an issue with downloading or building a custom package (`grunt build-custom`)?

**Comment by t-kawajiri** [comment]
@AMBudnik 
grunt build-custom works fine! thanks
