### ISSUE TITLE
Wrong declaration for ObserveChanges in hot-builder UI

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/hot-builder#18]
It is only an information error, custom package is build properly.

If I select `ColumnSorting` plugin I get automatically `ObserveChanges` plugin stated via `Included dependency` note. However it is marked as `excluded` from plugins below:

![observe-changes](https://cloud.githubusercontent.com/assets/10757813/21768406/d63fc366-d679-11e6-937e-8df42d07c432.png)

**Comment by budnix** [comment]
This is desirable behavior. It informs that a user has excluded `ObserveChanges` plugin from CLI so he can be sure that he passed the corrected arguments. Additionally, a user is informed that the plugin will be included as it is required by the `ColumnSorting` plugin.
