### ISSUE TITLE
List of the external libraries in PRO version, has got incorrect list of elements

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/hot-builder#19]
When you try to run `grunt build-custom`, on list of the external libraries you can see double elements.
![screen shot 2017-01-09 at 15 03 32](https://cloud.githubusercontent.com/assets/11849621/21768995/d24baa24-d67c-11e6-8559-740d1b323ff0.png)

**Comment by budnix** [comment]
Fixed and released in 1.0.0.
