### ISSUE TITLE
How to build a custom hot without moment and pikaday dependencies

### ISSUE THREAD

**Issue by PoiScript** [handsontable/hot-builder#26]
I don't need the Date cell feature, so that moment and pikaday is not needed. How to build a custom bundle that doesn't require moment and pikaday?

**Comment by AMBudnik** [comment]
Hi @PoiScript 

Please check this article about building a custom package using hot-builder https://handsontable.com/blog/articles/how-to-build-a-custom-version-of-handsontable

The MomentJS and Pikaday are a part of the core. You can try to use the Handsontable.min.js file (not full) and delete them manually but still, you'll need the formula dependencies (issue related https://github.com/handsontable/handsontable/issues/4693)

**Comment by PoiScript** [comment]
Ok, so it's no way to get rid of moment and pikaday without modifying the bundle manually? Beacuse I don't think it's a good way to edit the generated files by hand.

**Comment by AMBudnik** [comment]
Yes, it's not a good practice but generally, we allow to get rid of some unwanted plugins, not parts of the Core.

**Comment by PoiScript** [comment]
@AMBudnik thanks, closing.
