### ISSUE TITLE
Module moment not found

### ISSUE THREAD

**Issue by skosch** [handsontable/hot-builder#27]
Hi guys,

I'm running into

```
$ hot-builder build  --output-dir hot-dist
Creating custom build...

[✓] Cloning repository...                                           [finished]
[✓] Installing all necessary dependencies (it will take a while)... [finished]

Module moment not found
```
The repo gets cloned into `/home/sebastian/.nvm/versions/node/v7.4.0/lib/node_modules/hot-builder`.
Any ideas?

**Comment by Sundarcj** [comment]
am also getting same error ..
Anyone got solutions?

**Comment by swk777** [comment]
I got the same error?
anyone can help?

**Comment by AMBudnik** [comment]
Hi guys,

please track progress to https://github.com/handsontable/handsontable/issues/5287 for updates

**Comment by budnix** [comment]
[hot-builder](https://github.com/handsontable/hot-builder/releases/tag/4.0.0) has just been released. The 4.0.0 version resolves all issues related to external dependencies.
