### ISSUE TITLE
Some es6 operators not transpiled in dist output

### ISSUE THREAD

**Issue by anthonysimone** [handsontable/hot-builder#31]
I'm trying to use the hot-builder to generate a slimmed down version of handsontable. We use a pretty standard setup with npm, so I was thinking one option to incorporate this tool into that workflow would be to just publish a custom package with the customized `dist` output from hot builder and import that into the project as you would with the actual handsontable package.

I'm encountering issues with the `dist` folder output from the hot builder not transpiling some ES6 operators (I'm specifically seeing the spread and exponentiation operator). I'm wondering if this is an oversight and the dist output should be expected to be completely transpiled down to ES5, or if you're assuming some level of action on the consumer's side to further transpile the output of hot builder. Thanks for any feedback!

**Comment by anthonysimone** [comment]
Actually, just to followup here, even after running the output through babel to transpile those or just adding the output as a script tag to a browser that supports those operators, the output was still failing giving this error message. So this might actually be related to something else entirely, not what's in the title of this issue.

```
You may need an appropriate loader to handle this file type.
|       area = createHighlight(AREA_TYPE, {
|         layerLevel,
|         ...this.options
|       });
|       this.areas.set(layerLevel, area);
```

**Comment by AMBudnik** [comment]
Welcome @anthonysimone 

thank you very much for sharing the investigation results but not in the distant future we're planning to drop the development for the hot-builder

**Comment by anthonysimone** [comment]
Thanks for the update! Is there an alternate method planned for the future that will allow using hands on table with less than the full build if not necessary for your project?

**Comment by AMBudnik** [comment]
Not yet. We had plans to open a Marketplace but never made it.

**Comment by anthonysimone** [comment]
Cool, thanks for the context!
